[package]
name = "pylyzer"
description = "A static code analyzer & language server for Python"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/py2erg",
]

[workspace.package]
version = "0.0.1"
authors = ["Shunsuke Shibayama <sbym1346@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/mtshiba/pylyzer"

[workspace.dependencies]
erg_common = "0.6.0"
erg_compiler = "0.6.0"
els = "0.1.12"
rustpython-parser = "0.1.2"
# erg_compiler = { git = "https://github.com/erg-lang/erg", branch = "main" }
# erg_common = { git = "https://github.com/erg-lang/erg", branch = "main" }
# els = { git = "https://github.com/erg-lang/erg-language-server", branch = "main" }

[features]
debug = ["erg_compiler/debug", "erg_common/debug", "py2erg/debug"]

[dependencies]
erg_compiler = { workspace = true }
erg_common = { workspace = true }
els = { workspace = true }
rustpython-parser = { workspace = true }
py2erg = { version = "0.0.1", path = "./crates/py2erg" }

[lib]
path = "src/lib.rs"
