[package]
name = "pylyzer"
version = "0.0.1"
edition = "2021"
description = "A Python static code analyzer & language server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/py2erg",
]

[features]
debug = ["erg_compiler/debug", "erg_common/debug"]

[dependencies]
rustpython-parser = "0.1.2"
# erg_compiler = { git = "https://github.com/erg-lang/erg", branch = "main" }
# erg_common = { git = "https://github.com/erg-lang/erg", branch = "main" }
# els = { git = "https://github.com/erg-lang/erg-language-server", branch = "main" }
erg_common = "0.6.0"
erg_compiler = "0.6.0"
els = "0.1.12"
py2erg = { path = "./crates/py2erg" }

[lib]
path = "src/lib.rs"
